---
- hosts: all
  sudo: yes
  roles:
    - role: ansible-locale
      locale: en_US.UTF-8
      locale_language: en_US.UTF-8
      locale_lang: en_US.UTF-8
      locale_all: en_US.UTF-8
      locale_numeric: en_US.UTF-8
      locale_time: en_US.UTF-8
      locale_monetary: en_US.UTF-8
      locale_paper: en_US.UTF-8
      locale_identification: en_US.UTF-8
      locale_name: en_US.UTF-8
      locale_address: en_US.UTF-8
      locale_telephone: en_US.UTF-8
      locale_measurement: en_US.UTF-8
    - role: newrelic_infrastructure


- { hosts: app_servers, sudo: yes, roles: [ bennojoy.nginx], tags: [ bennojoy.nginx ]}

- { hosts: app_servers, sudo: yes, roles: [ app_server ], tags: [ app_server ]}

- hosts: app_servers
  sudo: yes
  roles:
    - role: sumologic-collector
      sumologic_installer_url: https://collectors.eu.sumologic.com/rest/download/deb/64
      sumologic_collector_name: jumo_ntw_logs_Collector
      when: APP_ENVIRONMENT != 'development'
      tags: [sumologic]

- hosts: db_servers
  sudo: yes
  roles:
    - role: Ansibles.postgresql
      postgresql_version: 9.3
      postgresql_ext_install_contrib: yes
      postgresql_ext_install_dev_headers: yes
      postgresql_ext_install_postgis: yes
      postgresql_databases: 
        - name: "{{ DB_NAME }}"
      postgresql_users:
        - name: "{{ DB_USER }}"
          pass: "{{ DB_PASSWORD }}"
      postgresql_user_privileges:
        - name: "{{ DB_USER }}" 
          db: "{{ DB_NAME }}"
          priv: ALL
      tags: 
        - db_server

- hosts: all
  sudo: yes
  roles:
    - role: modcloth-sumologic-collector
      sumologic_installer_url: https://collectors.eu.sumologic.com/rest/download/deb/64
      sumologic_collector_accessid: {{ SUMO_COLLECTOR_ACCESSID }}
      sumologic_collector_accesskey: {{ SUMO_COLLECTOR_ACCESSKEY }}
      sumologic_collector_name: {{ SUMO_COLLECTOR_NAME }}
      sumologic_collector_override: true
      sumologic_collector_source_template: sumo-sources.json.j2
      when: APP_ENVIRONMENT != 'development'
      tags: [sumologic]
