---
- hosts: all
  sudo: yes
  roles:
    - role: ansible-locale
      locale: en_US.UTF-8
      locale_language: en_US.UTF-8
      locale_lang: en_US.UTF-8
      locale_all: en_US.UTF-8
      locale_numeric: en_US.UTF-8
      locale_time: en_US.UTF-8
      locale_monetary: en_US.UTF-8
      locale_paper: en_US.UTF-8
      locale_identification: en_US.UTF-8
      locale_name: en_US.UTF-8
      locale_address: en_US.UTF-8
      locale_telephone: en_US.UTF-8
      locale_measurement: en_US.UTF-8
#    - role: newrelic_infrastructure


- { hosts: app_servers, sudo: yes, roles: [ bennojoy.nginx], tags: [ bennojoy.nginx ]}

- { hosts: app_servers, sudo: yes, roles: [ app_server ], tags: [ app_server ]}


- hosts: db_servers
  sudo: yes
  roles:
    - role: Ansibles.postgresql
      postgresql_version: 9.3
      postgresql_ext_install_contrib: yes
      postgresql_ext_install_dev_headers: yes
      postgresql_ext_install_postgis: yes
      postgresql_databases: 
        - name: "{{ DB_NAME }}"
      postgresql_users:
        - name: "{{ DB_USER }}"
          pass: "{{ DB_PASSWORD }}"
      postgresql_user_privileges:
        - name: "{{ DB_USER }}" 
          db: "{{ DB_NAME }}"
          priv: ALL
      tags: 
        - db_server

