# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 08:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_fsm
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer_wallet_management', '0009_auto_20170322_0927'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_trid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('processing', models.BooleanField(default=False)),
                ('batch_title', models.TextField(default=b'BATCHTRX')),
                ('batch_status', models.CharField(choices=[(b'created', b'created'), (b'finished', b'finished')], default=b'created', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_wallet_management.CustomerWallet')),
            ],
            options={
                'verbose_name': 'BatchTransaction',
                'verbose_name_plural': 'BatchTransactions',
            },
        ),
        migrations.CreateModel(
            name='BatchTransactionLookup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('batch_transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet_transactions.BatchTransaction')),
            ],
            options={
                'verbose_name': 'Batch Transaction Lookup',
                'verbose_name_plural': 'Batch Transactions Lookup',
            },
        ),
        migrations.CreateModel(
            name='DebitMandate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default=b'KES', max_length=10)),
                ('amount_limit', models.IntegerField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('number_of_payments', models.IntegerField()),
                ('frequency_type', models.CharField(choices=[(b'weekly', b'weekly'), (b'fortnight', b'fortnight'), (b'monthspecificdate', b'monthspecificdate'), (b'twomonths', b'twomonths'), (b'threemonths', b'threemonths'), (b'fourmonths', b'fourmonths'), (b'sixmonths', b'sixmonths'), (b'yearly', b'yearly'), (b'lastdaymonth', b'lastdaymonth'), (b'lastdaymonthworking', b'lastdaymonthworking'), (b'lastmonday', b'lastmonday'), (b'lasttuesday', b'lasttuesday'), (b'lastwednesday', b'lastwednesday'), (b'lastthursday', b'lastthursday'), (b'lastfriday', b'lastfriday'), (b'lastsaturday', b'lastsaturday'), (b'lastsunday', b'lastsunday'), (b'specificdaymonthly', b'specificdaymonthly')], max_length=20)),
                ('mandate_status', models.CharField(choices=[(b'active', b'active'), (b'inactive', b'inactive')], max_length=20)),
                ('request_date', models.DateTimeField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_wallet_management.CustomerWallet')),
                ('payee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payee', to='customer_wallet_management.CustomerWallet')),
                ('payer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payer', to='customer_wallet_management.CustomerWallet')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('currency', models.CharField(default=b'KES', max_length=10)),
                ('description_text', models.CharField(blank=True, max_length=100, null=True)),
                ('request_date', models.DateTimeField(default=datetime.datetime(2017, 3, 22, 11, 2, 19, 767092))),
                ('amount', models.IntegerField()),
                ('server_correlation_id', models.UUIDField(unique=True)),
                ('transaction_type', models.CharField(choices=[(b'reversal', b'reversal'), (b'billpay', b'billpay'), (b'deposit', b'deposit'), (b'transfer', b'transfer'), (b'withdrawal', b'withdrawal'), (b'disbursement', b'disbursement'), (b'merchantpay', b'merchantpay')], max_length=20)),
                ('callback_url', models.URLField(blank=True, null=True)),
                ('state', django_fsm.FSMField(choices=[(b'pending', b'pending'), (b'in_progress', b'in_progress'), (b'completed', b'completed'), (b'failed', b'failed'), (b'reversed', b'reversed')], default=b'pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_destination', to='customer_wallet_management.CustomerWallet')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_source', to='customer_wallet_management.CustomerWallet')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.CreateModel(
            name='WalletTopupTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=64)),
                ('amount', models.IntegerField()),
                ('currency', models.CharField(default=b'KES', max_length=10)),
                ('bank_reference', models.CharField(max_length=64)),
                ('deposit_timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_wallet_management.CustomerWallet')),
            ],
            options={
                'verbose_name': 'Wallet Top-up Transaction',
                'verbose_name_plural': 'Wallet Top-up Transactions',
            },
        ),
        migrations.AddField(
            model_name='batchtransactionlookup',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet_transactions.Transaction'),
        ),
    ]
