# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-14 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer_wallet_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkTransaction',
            fields=[
                ('bulk_transaction_id', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_wallet_management.CustomerWallet')),
            ],
            options={
                'verbose_name': 'Bulk Transaction',
                'verbose_name_plural': 'Bulk Transactions',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('amount', models.IntegerField()),
                ('type', models.CharField(choices=[(b'reversal', b'reversal'), (b'payment', b'payment'), (b'deposit', b'deposit'), (b'withdrawal', b'withdrawal'), (b'statement', b'statement'), (b'p2p', b'p2p')], max_length=20)),
                ('state', models.CharField(choices=[(b'received', b'received'), (b'in_progress', b'in_progress'), (b'completed', b'completed')], default=b'received', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tansaction_destination', to='customer_wallet_management.CustomerWallet')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tansaction_source', to='customer_wallet_management.CustomerWallet')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
    ]
