# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debitmandate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='debitmandate',
            name='mandate_reference',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name='debitmandate',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='trid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
