# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-14 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkTransactionLookup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('bulk_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet_transactions.BulkTransaction')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet_transactions.Transaction')),
            ],
            options={
                'verbose_name': 'Bulk Transaction Lookup',
                'verbose_name_plural': 'Bulk Transactions Lookup',
            },
        ),
    ]
