# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_transactions', '0002_auto_20170322_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitmandate',
            name='frequency_type',
            field=models.CharField(choices=[(b'weekly', b'weekly'), (b'fortnight', b'fortnight'), (b'monthspecificdate', b'monthspecificdate'), (b'twomonths', b'twomonths'), (b'threemonths', b'threemonths'), (b'fourmonths', b'fourmonths'), (b'sixmonths', b'sixmonths'), (b'yearly', b'yearly'), (b'lastdaymonth', b'lastdaymonth'), (b'lastdaymonthworking', b'lastdaymonthworking'), (b'lastmonday', b'lastmonday'), (b'lasttuesday', b'lasttuesday'), (b'lastwednesday', b'lastwednesday'), (b'lastthursday', b'lastthursday'), (b'lastfriday', b'lastfriday'), (b'lastsaturday', b'lastsaturday'), (b'lastsunday', b'lastsunday'), (b'specificdaymonthly', b'specificdaymonthly'), (b'minutely', b'minutely')], max_length=20),
        ),
    ]
