# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-16 16:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_transactions', '0002_bulktransactionlookup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bulktransaction',
            options={'verbose_name': 'BulkTransaction', 'verbose_name_plural': 'BulkTransactions'},
        ),
    ]
