# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 20:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_transactions', '0003_auto_20170322_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debitmandate',
            name='account',
        ),
    ]
