# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-16 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer_wallet_management', '0006_auto_20170316_1316'),
        ('wallet_transactions', '0003_auto_20170316_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_trid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_wallet_management.CustomerWallet')),
            ],
            options={
                'verbose_name': 'BatchTransaction',
                'verbose_name_plural': 'BatchTransactions',
            },
        ),
        migrations.CreateModel(
            name='BatchTransactionLookup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('batch_transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet_transactions.BatchTransaction')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet_transactions.Transaction')),
            ],
            options={
                'verbose_name': 'Batch Transaction Lookup',
                'verbose_name_plural': 'Batch Transactions Lookup',
            },
        ),
        migrations.RemoveField(
            model_name='bulktransaction',
            name='merchant',
        ),
        migrations.RemoveField(
            model_name='bulktransactionlookup',
            name='bulk_transaction',
        ),
        migrations.RemoveField(
            model_name='bulktransactionlookup',
            name='transaction',
        ),
        migrations.DeleteModel(
            name='BulkTransaction',
        ),
        migrations.DeleteModel(
            name='BulkTransactionLookup',
        ),
    ]
