# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_transactions', '0004_remove_debitmandate_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[(b'reversal', b'reversal'), (b'billPay', b'billPay'), (b'deposit', b'deposit'), (b'transfer', b'transfer'), (b'withdrawal', b'withdrawal'), (b'disbursement', b'disbursement'), (b'merchantPayment', b'merchantPayment')], max_length=20),
        ),
    ]
