# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 10:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_transactions', '0004_auto_20170316_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_destination', to='customer_wallet_management.CustomerWallet'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_source', to='customer_wallet_management.CustomerWallet'),
        ),
    ]
