# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_transactions', '0005_auto_20170323_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchtransaction',
            name='merchant',
        ),
        migrations.AlterField(
            model_name='batchtransaction',
            name='batch_status',
            field=models.CharField(choices=[(b'created', b'created'), (b'approved', b'approved'), (b'completed', b'completed')], default=b'created', max_length=20),
        ),
    ]
