# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_transactions', '0006_auto_20170317_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='server_correlation_id',
            field=models.UUIDField(default='753bcd19-7230-40ba-a975-09ac94ace0d2', unique=True),
            preserve_default=False,
        ),
    ]
