# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_transactions', '0007_transaction_server_correlation_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='type',
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(default=b'KES', max_length=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[(b'reversal', b'reversal'), (b'payment', b'payment'), (b'deposit', b'deposit'), (b'transfer', b'transfer'), (b'withdrawal', b'withdrawal'), (b'statement', b'statement'), (b'p2p', b'p2p')], default='transfer', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='state',
            field=models.CharField(choices=[(b'pending', b'pending'), (b'in_progress', b'in_progress'), (b'completed', b'completed'), (b'failed', b'failed')], default=b'pending', max_length=20),
        ),
    ]
