# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_transactions', '0008_auto_20170319_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='callback_url',
            field=models.URLField(null=True),
        ),
    ]
