# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-20 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_transactions', '0009_transaction_callback_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchtransaction',
            name='batch_status',
            field=models.CharField(choices=[(b'created', b'created'), (b'finished', b'finished')], default=b'created', max_length=20),
        ),
        migrations.AddField(
            model_name='batchtransaction',
            name='batch_title',
            field=models.TextField(default=b'BATCHTRX'),
        ),
        migrations.AddField(
            model_name='batchtransaction',
            name='processing',
            field=models.BooleanField(default=False),
        ),
    ]
