# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_transactions', '0010_auto_20170320_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='description_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
