# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 12:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_transactions', '0011_transaction_description_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='request_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
