# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 18:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_transactions', '0012_auto_20170320_2004'),
        ('wallet_transactions', '0011_auto_20170320_1926'),
    ]

    operations = [
    ]
