# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_transactions', '0012_transaction_request_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='callback_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
