# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_transactions', '0013_merge_20170320_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='state',
            field=models.CharField(choices=[(b'pending', b'pending'), (b'in_progress', b'in_progress'), (b'completed', b'completed'), (b'failed', b'failed'), (b'reversed', b'reversed')], default=b'pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[(b'reversal', b'reversal'), (b'payment', b'payment'), (b'deposit', b'deposit'), (b'transfer', b'transfer'), (b'withdrawal', b'withdrawal')], max_length=20),
        ),
    ]
