# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 12:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_transactions', '0013_auto_20170320_1553'),
        ('wallet_transactions', '0014_auto_20170320_2124'),
    ]

    operations = [
    ]
