# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 12:22
from __future__ import unicode_literals

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_transactions', '0014_auto_20170320_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='state',
            field=django_fsm.FSMField(choices=[(b'pending', b'pending'), (b'in_progress', b'in_progress'), (b'completed', b'completed'), (b'failed', b'failed'), (b'reversed', b'reversed')], default=b'pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[(b'reversal', b'reversal'), (b'billpay', b'billpay'), (b'deposit', b'deposit'), (b'transfer', b'transfer'), (b'withdrawal', b'withdrawal'), (b'disbursement', b'disbursement'), (b'merchantpay', b'merchantpay')], max_length=20),
        ),
    ]
