# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 12:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_transactions', '0015_merge_20170321_1530'),
        ('wallet_transactions', '0015_auto_20170321_1522'),
    ]

    operations = [
    ]
