# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 06:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_transactions', '0016_merge_20170321_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 22, 9, 27, 0, 281369)),
        ),
    ]
