# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 07:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_wallet_management', '0008_auto_20170320_1550'),
        ('wallet_transactions', '0019_auto_20170322_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='debitmandate',
            name='payee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payee', to='customer_wallet_management.CustomerWallet'),
        ),
        migrations.AddField(
            model_name='debitmandate',
            name='payer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payer', to='customer_wallet_management.CustomerWallet'),
        ),
    ]
