# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-15 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_wallet_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerwallet',
            name='status',
            field=models.CharField(choices=[(b'active', b'active'), (b'dormant', b'dormant'), (b'inactive', b'inactive')], default=b'active', max_length=20),
        ),
    ]
