# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-16 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_wallet_management', '0003_auto_20170316_1240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerwallet',
            options={'verbose_name': 'Account', 'verbose_name_plural': 'Accounts'},
        ),
    ]
