# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-16 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer_wallet_management', '0004_auto_20170316_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerwallet',
            name='wallet_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
