# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_wallet_management', '0007_auto_20170320_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerwallet',
            name='token',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
