# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_wallet_management', '0008_auto_20170320_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerwallet',
            name='type',
            field=models.CharField(choices=[(b'normal', b'normal'), (b'merchant', b'merchant'), (b'agent', b'agent')], default=b'normal', max_length=20),
        ),
    ]
