# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 07:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification_management', '0002_auto_20170321_1522'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationdevicemap',
            options={'verbose_name': 'Notification DeviceMap', 'verbose_name_plural': 'Notification DeviceMaps'},
        ),
    ]
