# file: postgresql/tasks/extensions/dev_headers.yml

- name: PostgreSQL | Extensions | Make sure the development headers are installed
  apt:
    name: "postgresql-contrib-{{postgresql_version}}"
    state: present
  notify:
    - restart postgresql
