# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-14 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msisdn', models.CharField(max_length=20, unique=True)),
                ('token', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[(b'normal', b'normal'), (b'merchant', b'merchant')], default=b'normal', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
