---
# tasks
- name: Write newrelic-infra.yml
  template: dest=/tmp/newrelic-infra.yml
            src=newrelic-infra.yml.j2
            backup=yes

- name: Write newrelic.ini file
  template: dest=/tmp/newrelic.ini
            src=newrelic.ini.j2
            backup=yes

- name: enable newrelic gpg key
  shell: curl -vkL https://download.newrelic.com/infrastructure_agent/gpg/newrelic-infra.gpg | sudo apt-key add -

- name: add newrelic apt repo
  shell: printf "deb [arch=amd64] https://download.newrelic.com/infrastructure_agent/linux/apt trusty main" | sudo tee -a /etc/apt/sources.list.d/newrelic-infra.list

- name: apt update
  shell: sudo apt-get -y update

- name: install newrelic infra agent 
  shell: sudo apt-get -y install newrelic-infra
  when: APP_ENVIRONMENT != "development"

- name: subsititute newrelic key from env in infra yml
  shell: envsubst < /tmp/newrelic-infra.yml > /etc/newrelic-infra.yml

- name: subsititute newrelic key from env in newrelic ini file
  shell: envsubst < /tmp/newrelic.ini > /etc/newrelic.ini
