# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 17:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer_wallet_management', '0008_auto_20170320_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default=b'KES', max_length=10)),
                ('amount_due', models.IntegerField()),
                ('due_date', models.DateField()),
                ('bill_reference', models.UUIDField(unique=True)),
                ('min_amount_due', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('billee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billee', to='customer_wallet_management.CustomerWallet')),
                ('biller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biller', to='customer_wallet_management.CustomerWallet')),
            ],
            options={
                'verbose_name': 'Bill',
                'verbose_name_plural': 'Bills',
            },
        ),
    ]
