# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
