# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_management', '0003_auto_20170323_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill_status',
            field=models.CharField(choices=[(b'unpaid', b'updaid'), (b'paid', b'paid')], default=b'unpaid', max_length=20),
        ),
    ]
